apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tflannag-runner-service-account
  labels:
    app: runner
subjects:
- kind: ServiceAccount
  name: runner
  namespace: tflannag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tflannag-runner-service-account
