apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      serviceAccountName: runner
      containers:
      - name: exporter
        image: quay.io/tflannag/promscale:latest
        imagePullPolicy: Always
        args:
        - exec
        - --postgres-address=postgres.tflannag.svc
        - --postgres-port=5432
        - --log-level=debug
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 250Mi
